apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - replicaset.yaml
  - service.yaml
  - target_group_binding.yaml
  - service-account.yaml
  - security_group_policy.yaml

namespace: k8s-application
