apiVersion: v1
kind: Pod
metadata:
  name: k8s-application-pod
  labels:
    app: k8s-application
spec:
  containers:
  - name: k8s-application-nginx
    image: nginx:latest
    ports:
    - containerPort: 80
      name: http
      protocol: TCP