apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: k8s-application-nginx-replicaset
  labels:
    app: k8s-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-application
  template:
    metadata:
      labels:
        app: k8s-application
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: k8s-application-nginx
        image: 083636136646.dkr.ecr.ap-northeast-1.amazonaws.com/k8s-application-nginx:20250612v2
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
