apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-application-sa
  namespace: k8s-application
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::083636136646:role/K8sApplicationRole"
